version: '3.8'

services:
  transaction:
    build: .
    container_name: transaction
    ports:
      - "8000:8000"
    networks:
      - app_net
networks:
  app_net:
    external:
      name: homework1_app-network

